package conf

import "github.com/spf13/viper"

func set_defaults(v *viper.Viper) {
	v.SetDefault("defaultldap.host", "127.0.0.1")
	v.SetDefault("defaultldap.port", 389)
	v.SetDefault("defaultldap.auth_type", "directbind")
	v.SetDefault("defaultldap.bind_dn", "")
	v.SetDefault("defaultldap.bind_password", "")
	v.SetDefault("defaultldap.user_search_filter", "(uid=%s)")
	v.SetDefault("defaultldap.user_search_base", "ou=users,dc=example,dc=org")
	v.SetDefault("defaultldap.user_dn_template", "uid=%s,ou=users,dc=example,dc=org")
	v.SetDefault("defaultldap.username_attribute", "uid")
	v.SetDefault("defaultldap.mail_attribute", "mail")
	v.SetDefault("defaultldap.return_mail", false)
	v.SetDefault("defaultldap.tls_type", "none")
	v.SetDefault("defaultldap.certificate_authority", "")
	v.SetDefault("defaultldap.certificate", "")
	v.SetDefault("defaultldap.key", "")
	v.SetDefault("defaultldap.insecure", false)

	v.SetDefault("http.bind_addr", "0.0.0.0")
	v.SetDefault("http.port", 8080)
	v.SetDefault("http.realm", "Example Realm")
	v.SetDefault("http.authorization_header", "Authorization")
	v.SetDefault("http.authenticate_header", "WWW-Authenticate")
	v.SetDefault("http.original_uri_header", "X-Original-Uri")
	v.SetDefault("http.original_host_header", "X-Forwarded-Host")
	v.SetDefault("http.original_server_header", "X-Forwarded-Server")
	v.SetDefault("http.original_port_header", "X-Forwarded-Port")
	v.SetDefault("http.original_proto_header", "X-Forwarded-Proto")
	v.SetDefault("http.real_ip_header", "X-Real-Ip")
	v.SetDefault("http.remote_user_header", "X-Remote-User")
	v.SetDefault("http.jwt_header", "X-Remote-Jwt")
	v.SetDefault("http.login_uri_header", "X-Login-Uri")
	v.SetDefault("http.failed_auth_delay_seconds", 2)
	v.SetDefault("http.shutdown_timeout_seconds", 2)
	v.SetDefault("http.https", false)
	v.SetDefault("http.certificate", "")
	v.SetDefault("http.key", "")
	v.SetDefault("http.mask_password", false)
	v.SetDefault("http.login_tpl_path", "")
	v.SetDefault("http.login_tpl", "")
	v.SetDefault("http.error_message", "Authentication failed")

	v.SetDefault("api.bind_addr", "127.0.0.1")
	v.SetDefault("api.port", 8081)

	v.SetDefault("cache.expires", "24h")
	v.SetDefault("cache.secret", "")
	v.SetDefault("cache.cookie_header", "X-Nal-Cookie")
	v.SetDefault("cache.cookie_name", "BOUNCER_COOKIE")

	v.SetDefault("redis.host", "127.0.0.1")
	v.SetDefault("redis.port", 6379)
	v.SetDefault("redis.database", 0)
	v.SetDefault("redis.password", "")
	v.SetDefault("redis.poolsize", 10)
	v.SetDefault("redis.enabled", false)
	v.SetDefault("redis.expires_seconds", 86400)

	v.SetDefault("signature.private_key_path", "")
	v.SetDefault("signature.private_key_content", "")
}
